class LocalStorageKeys {
  static const String token = "token";
  static const String refreshToken = "refreshToken";
  static const String isLogIn = "isLogIn";
  static const String businessName = "businessName";
  static const String phone = "phone";
  static const String userId = "userId";
  static const String businessLogo = "businessLogo";
  static const String address = "address";
  static const String businessType = "businessType";
  static const String businessLicenceNumber = "businessLicenceNumber";
  static const String myImage = "myImage";
  static const String advertiserBio = "advertiserBio";
  static const String myName = "myName";
  static const String myEmail = "myEmail";
  static const String myRole = "myRole";
  static const String role = "role";
  static const String activeRole = "activeRole"; // Used to track current viewing mode
  static const String mobile = "mobile";
  static const String dateOfBirth = "dateOfBirth";
  static const String gender = "gender";
  static const String experience = "experience";
  static const String balance = "balance";
  static const String verified = "verified";
  static const String bio = "bio";
  static const String lat = "lat";
  static const String log = "log";
  static const String accountInfoStatus = "accountInfoStatus";
  static const String createdAt = "createdAt";
  static const String updatedAt = "updatedAt";
  static const String forgotPasswordToken="forgotPasswordToken";
}
