// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF-lhysIGp70ybVIUL5SI-jQRLER3DQlY',
    appId: '1:627654989285:web:69e2760b83937bc6570b0c',
    messagingSenderId: '627654989285',
    projectId: 'just-clicker-count',
    authDomain: 'just-clicker-count.firebaseapp.com',
    storageBucket: 'just-clicker-count.firebasestorage.app',
    measurementId: 'G-N65RHV8Z27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA__bw6gjpQq_eHPoO66CpawG5txciXO34',
    appId: '1:627654989285:android:22ef48ae63970498570b0c',
    messagingSenderId: '627654989285',
    projectId: 'just-clicker-count',
    storageBucket: 'just-clicker-count.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB16YCc0fCynKRbN6OV786uSaYEfNkbCE4',
    appId: '1:627654989285:ios:921cea125033fb1c570b0c',
    messagingSenderId: '627654989285',
    projectId: 'just-clicker-count',
    storageBucket: 'just-clicker-count.firebasestorage.app',
    iosBundleId: 'com.justmetaverse.justclicker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB16YCc0fCynKRbN6OV786uSaYEfNkbCE4',
    appId: '1:627654989285:ios:0279ab777aa01361570b0c',
    messagingSenderId: '627654989285',
    projectId: 'just-clicker-count',
    storageBucket: 'just-clicker-count.firebasestorage.app',
    iosBundleId: 'com.justmetaverse.justclicker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF-lhysIGp70ybVIUL5SI-jQRLER3DQlY',
    appId: '1:627654989285:web:ba27084508340ffe570b0c',
    messagingSenderId: '627654989285',
    projectId: 'just-clicker-count',
    authDomain: 'just-clicker-count.firebaseapp.com',
    storageBucket: 'just-clicker-count.firebasestorage.app',
    measurementId: 'G-RBKG1FBDXB',
  );
}
